OdeToFood/Controllers/RecipeReviewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OdeToFood.Models;
using PagedList;

namespace OdeToFood.Controllers
{
    public class RecipeReviewsController : Controller
    {
        private OdeToFoodDb db = new OdeToFoodDb();

        public ActionResult SeeReviewersRecipes(string r)
        {
            var model = db.RecipeReviews.Where(m => m.ReviewerName == r);
            return View("GetMyRecipeReviews", model);
        }

        public ActionResult GetMyRecipeReviews(int page = 1)
        {
            var UserReviews = db.RecipeReviews.Where(m => m.ReviewerName == User.Identity.Name).ToList().ToPagedList(page, 10);
            return View(UserReviews);
        }

        public ActionResult Modal(int recipeId)
        {
            //RestaurantReview review = new RestaurantReview();
            return View("ModalRecipe");
        }

        // GET: RecipeReviews
        public ActionResult Index([Bind(Prefix = "id")] int recipeId)
        {
             var recipe = db.Recipes.Find(recipeId);
            if (recipe != null)
            {
                return View(recipe);

            }
            return HttpNotFound();
        }

        // GET: RecipeReviews/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RecipeReview recipeReview = db.RecipeReviews.Find(id);
            if (recipeReview == null)
            {
                return HttpNotFound();
            }
            return View(recipeReview);
        }

        // GET: RecipeReviews/Create
        public ActionResult Create(int recipeId)
        {
            return PartialView("ModalRecipe");
        }


        // POST: RecipeReviews/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RecipeReview recipeReview)
        {
            if (ModelState.IsValid)
            {
                recipeReview.ReviewerName = User.Identity.Name;
                db.RecipeReviews.Add(recipeReview);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = recipeReview.RecipeId });
            }

            return View(recipeReview);
        }

        // GET: RecipeReviews/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RecipeReview recipeReview = db.RecipeReviews.Find(id);
            if (recipeReview == null)
            {
                return HttpNotFound();
            }
            ViewBag.RecipeId = new SelectList(db.Recipes, "Id", "Name", recipeReview.RecipeId);
            return View(recipeReview);
        }

        // POST: RecipeReviews/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Rating,Title,Body,ReviewerName,RecipeId")] RecipeReview recipeReview)
        {
            if (ModelState.IsValid)
            {
                db.Entry(recipeReview).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.RecipeId = new SelectList(db.Recipes, "Id", "Name", recipeReview.RecipeId);
            return View(recipeReview);
        }

        // GET: RecipeReviews/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RecipeReview recipeReview = db.RecipeReviews.Find(id);
            if (recipeReview == null)
            {
                return HttpNotFound();
            }
            return View(recipeReview);
        }

        // POST: RecipeReviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RecipeReview recipeReview = db.RecipeReviews.Find(id);
            db.RecipeReviews.Remove(recipeReview);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OdeToFood/Controllers/ReviewsController.cs
using OdeToFood.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace OdeToFood.Controllers
{
    public class ReviewsController : Controller
    {
        OdeToFoodDb _db = new OdeToFoodDb();

        //[ChildActionOnly]//This would ensure that this contoller cannot be called through the URL
        //public ActionResult BestReview()//This action will display the besst rated review from the lisr of review, at the bottom of every page (because it is called from the shared _Layout View).
        //{
        //    var bestReview = from r in _reviews
        //                     orderby r.Rating descending
        //                     select r;

        //    return PartialView("_Review", bestReview.First());
        //}

        public ActionResult SeeReviewersRestaurantsReviews(string r)
        {
            var model = _db.Reviews.Where(m => m.ReviewerName == r);
            return View("GetMyReviews", model);
        }


        public ActionResult GetMyReviews(int page = 1)
        {
            var UserReviews = _db.Reviews.Where(m => m.ReviewerName == User.Identity.Name).ToList().ToPagedList(page, 10);
            return View(UserReviews);
        }
        
        public ActionResult BestReviews(int page = 1)
        {
            var model = _db.Reviews.Where(m => m.Rating == 10).ToList().ToPagedList(page, 10);
            return View(model);
        }

        public ActionResult Test(int restaurantId)
        {
            //RestaurantReview review = new RestaurantReview();
            return View("_Test");
        }

        // GET: Reviews
        public ActionResult Index([Bind(Prefix = "id")] int restaurantId)  //This says when looking for the restaurantId parameter value, instead look for something called 'id'.
        {
            var restaurant = _db.Restaurants.Find(restaurantId);
            if (restaurant != null)
            {
                return View(restaurant);

            }
            return HttpNotFound();
        }

       

        [HttpGet]
        
        public ActionResult Create(int restaurantId)
        {
            return PartialView("_Test");
        }
        
        
        [HttpPost]
        public ActionResult Create(RestaurantReview review)
        {
            if (ModelState.IsValid)
            {
                review.ReviewerName = User.Identity.Name;
                _db.Reviews.Add(review);//If IsValid returns true, then add this review to the Reviews collections
                _db.SaveChanges();//This will actually save it to the database
                return RedirectToAction("Index", new { id = review.RestaurantId });//Second paramter ensures the user can then view their newly entered review (as we've passed the id through).
                

            }
            return View(review);//Passing 'review' as a parameter here ensures that the user doesn't lose their already inputted data.
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = _db.Reviews.Find(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(RestaurantReview review)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(review).State = EntityState.Modified;//Here is a review i want you to track so you can make changes in the database, but its not a new review so I don't want it inserted into the database. Instead its a review that's already in the database.
                _db.SaveChanges();
                return RedirectToAction("Index", new { id = review.RestaurantId });
            }
            return View(review);
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RestaurantReview restaurantReview = _db.Reviews.Find(id);
            if (restaurantReview == null)
            {
                return HttpNotFound();
            }
            return View(restaurantReview);
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);    
        }


    }
}

OdeToFood/Views/Reviews/BestReviews.cshtml
@model IPagedList<OdeToFood.Models.RestaurantReview>

@{
    ViewBag.Title = "BestReviews";
}

<h2 class="text-center py-4">Best Reviews</h2>

<div class="text-center py-4">
    <button type="button" class="btn btn-success btn-lg mx-auto my-Z" onclick="window.location='@Request.UrlReferrer.AbsoluteUri'">Back</button>
</div>

<div class="container pl-4">
    <table class="table">
        <tr>
            <th>
                Restaurant Name
            </th>
            <th>
                Rating
            </th>
            <th>
                Title
            </th>
            <th>
                Reviewer Name
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a href="@Url.Action("Details", "Restaurant", new { id = item.RestaurantId })">@Html.DisplayFor(modelItem => item.RestaurantName.Name)</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    <a href="@Url.Action("SeeReviewersRecipes", "RecipeReviews", new { r = item.ReviewerName })">@Html.DisplayFor(modelItem => item.ReviewerName)</a>
                </td>
                <td>
                    <div class="pull-right">

                        <a href="@Url.Action("Details", new { id = item.Id })" class="btn btn-info btn-sm margin-right">
                            <span class="glyphicon glyphicon-list"></span>See More
                        </a>
                        @if (item.ReviewerName == User.Identity.Name)
                        {
                            <a href="@Url.Action("Details", new { id = item.Id })" class="btn btn-danger btn-sm margin-right">
                                <span class="glyphicon glyphicon-list"></span>My Entry
                            </a>
                        }
                    </div>       

                </td>
            </tr>
        }

    </table>
</div>
<div class="pl-5">
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount<!--Displays what page the user is on e.g. Page 1 of 2-->
    @Html.PagedListPager(Model, page => Url.Action("BestReviews", new { page }))
</div>

OdeToFood/Views/Reviews/Create.cshtml
@model OdeToFood.Models.RestaurantReview

@{
    ViewBag.Title = "Create";
    Layout = null;
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>New Review</h4>
        <hr />
        @Html.HiddenFor(m => m.ReviewerName)

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReviewerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReviewerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReviewerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RestaurantId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RestaurantId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RestaurantId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @*The below code won't work and I dont know why*@
    @*@Html.ActionLink("Back to List", "Index", new { id = Model.RestaurantId })*@
</div>

OdeToFood/Views/Reviews/Details.cshtml
@model OdeToFood.Models.RestaurantReview

@{
    ViewBag.Title = "Details";
}

<h2 class="text-center py-4">Details</h2>

<div class="text-center">
    <h4>@Model.RestaurantName.Name</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReviewerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReviewerName)
        </dd>
        
    </dl>
</div>
    <p class="text-center">
    @Html.ActionLink("Back to List", "Index", new { id = Model.RestaurantId }, new { @class = "btn btn-success" })
    <!--These options only display if the entry belongs to the user-->
    @if (Model.ReviewerName == User.Identity.Name)
    {


        <a href="@Url.Action("Edit", "Restaurant", new { id = Model.Id })" class="btn btn-warning">Edit</a>
        <a href="@Url.Action("Delete", "Restaurant", new { id = Model.Id })" class="btn btn-danger">Delete</a>
    
    }
   </p>

OdeToFood/Views/Reviews/Edit.cshtml
@model OdeToFood.Models.RestaurantReview

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Edit Review</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)<!--Will allow us to track the id of the review that is being edited and its because the user doesn't need to see it. -->

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReviewerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReviewerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReviewerName, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.RestaurantId) <!--So we can keep track of the restaurantId -->

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {

}

OdeToFood/Views/Reviews/GetMyReviews.cshtml
@model IPagedList<OdeToFood.Models.RestaurantReview>


@{
    ViewBag.Title = "GetMyReviews";
}

<h2 class="text-center py-4">Restaurant Reviews for @User.Identity.Name</h2>
<div class="text-center py-4">
    <button type="button" class="btn btn-success btn-lg mx-auto my-Z" onclick="window.location='@Request.UrlReferrer.AbsoluteUri'">Back</button>
</div>

<div class="container pl-4">
    <table class="table">
        <tr>
            <th>
                Restaurant Name
            </th>
            <th>
                Rating
            </th>
            <th>
               Title
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a href="@Url.Action("Details", "Restaurant", new { id = item.RestaurantId })">@Html.DisplayFor(modelItem => item.RestaurantName.Name)</a> <!--Allows user to click on link to be brought to the particular restaurant-->
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
              
                <td>
                     <a href="@Url.Action("Details", new { id = item.Id })" class="btn btn-info btn-sm margin-right">
                        <span class="glyphicon glyphicon-list">See More</span>
                    </a>
                   
                </td>
            </tr>
        }
    </table>
</div>
<div class="pl-5">
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount<!--Displays what page the user is on e.g. Page 1 of 2-->
    @Html.PagedListPager(Model, page => Url.Action("DisplayList", new { page }))
</div>

OdeToFood/Views/Reviews/Index.cshtml
@model OdeToFood.Models.Restaurant

@{ 
    ViewBag.Title = "Index";
}

@if (Model.Reviews.Count != 0)
{
    <h2 class="text-center pt-3">Reviews for @Model.Name</h2>
    if (Request.IsAuthenticated)
    {
      <button type="button" class="btn btn-info btn-lg d-block mx-auto my-5" data-toggle="modal" data-target="#register">Add Review</button>
    }

    <!--This partial view will display the list of current revies for the particular restaurant-->
    @Html.Partial("_Reviews", Model.Reviews)<!--Here we are passing the Reviews (a collection of Reviews) that are associated with the Restaurant to the PartialView. (Model.Reviews is the object we are passing through as the second parameter)-->
    <div class="text-center">
        <button type="button" class="btn btn-warning btn-lg mx-auto my-Z" onclick="window.location='@Request.UrlReferrer.AbsoluteUri'">Back</button>

    </div>
}
else
{
    @Html.Partial("_NoMatches")
    if (Request.IsAuthenticated)
    {
        <button type="button" class="btn btn-info btn-lg d-block mx-auto my-5" data-toggle="modal" data-target="#register">Add Review</button>
    }
    <div class="text-center">
        <a href="@Url.Action("Details", "Restaurant", new { id = Model.Id })" class="btn btn-warning btn-lg mx-auto my-Z">Back</a><!--A simple back button to return to the previous page-->
    </div>
}


<!--==========================
         FORM MODAL
 ===========================-->
<!--Modals are set to hidden by default, so it doesn't show up in the webpage. Rather you have to trigger their display by using a button-->
<div id="register" class="modal fade">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-info text-white">
                <h5 class="modal-title">Create Review</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @{Html.RenderAction("Test", "Reviews", new { restaurantId = Model.Id });}
            </div>
        </div>
    </div><!--End of Modal Dialog-->
</div><!--End of Modal-->


OdeToFood/Views/Reviews/_NoMatches.cshtml
@model OdeToFood.Models.Restaurant


<h1 class="text-center pt-4">There are currently no reviews for @Model.Name</h1>

OdeToFood/Views/Reviews/_Reviews.cshtml
@model IEnumerable<OdeToFood.Models.RestaurantReview>
@using OdeToFood.Models



<div class="container pl-4">
    <table class="table">
        <tr>
           
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>     
            <th>
                @Html.DisplayNameFor(model => model.ReviewerName)
            </th>
            <th>Details</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    <a href="@Url.Action("SeeReviewersRestaurantsReviews", "Reviews", new { r = item.ReviewerName })">@Html.DisplayFor(modelItem => item.ReviewerName)</a>
                </td>
                <td>
                    <a href="@Url.Action("Details", new { id = item.Id })" class="btn btn-info btn-sm margin-right">
                        See More
                    </a>
                    @if (item.ReviewerName == User.Identity.Name)
                        {
                            <a href="@Url.Action("Details", new { id = item.Id })" class="btn btn-danger btn-sm margin-right">
                                My Entry
                            </a>
                        }
                </td>
            </tr>
        }
    </table>
</div>

OdeToFood/Views/Reviews/_Test.cshtml
@model OdeToFood.Models.RestaurantReview

@{
    ViewBag.Title = "_Test";
    Layout = null; //Ensures that the navigation bar doesn't appear in the Modal.
}



@using (Html.BeginForm("Create", "Reviews", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h3>New Review</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" }) (From 1 to 10)
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Body, 7,40, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(m=> m.ReviewerName)<!--Two hidden proerties are sent with the form. The Reviewer's name will be set in the controller-->
        @Html.HiddenFor(m=>m.RestaurantId)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}