OdeToFood/Models/Restaurant.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace OdeToFood.Models
{
    public class Restaurant
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }
     
        //[MaxLength(200, ErrorMessage = "The Description cannot be long than 200 characters")]
        public string Description { get; set; }
        public string Keyword { get; set; }
        public string City { get; set; }
        [Display(Name= "User Name")]
        public string UserName { get; set; }
        [Display(Name ="Date Added")]
        public DateTime? Date { get; set; }

        
        public virtual ICollection<RestaurantReview> Reviews { get; set; } //By addding virtual I am ensuring that Reviews isn't null by default
        public string ImageFileName
        {
            get
            {
                return Name.Replace(" ", "-").ToLower() + ".jpg";
            }
        }
        public string ImagePath { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }
       
        
    }
}

OdeToFood/Controllers/RecipesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OdeToFood.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using PagedList;

namespace OdeToFood.Controllers
{
    public class RecipesController : Controller
    {
        private OdeToFoodDb db = new OdeToFoodDb();

        public ActionResult ByDateWeek(int page = 1)
        {
            var date = DateTime.Now.Date.AddDays(-7);
            var model = db.Recipes.Where(m => m.Date >= date).ToList().ToPagedList(page, 10); ;//Getting the Restaurants that were added in the past 7 days.
            ViewBag.MyDate = "7 Days";
            return View("DisplayList", model);
        }

        public ActionResult ByDateMonth(int page = 1)
        {
            var date = DateTime.Now.Date.AddDays(-30);
            var model = db.Recipes.Where(m => m.Date >= date).ToList().ToPagedList(page, 10);//Getting the Restaurants that were added in the past 30 days.
            ViewBag.MyDate = "30 Days";
            return View("DisplayList", model);
        }

        public ActionResult GetRecipes(int page = 1)
        {
            var UserRecipes = db.Recipes.Where(m => m.UserName == User.Identity.Name).ToList().ToPagedList(page, 10); 
            return View(UserRecipes);
        }

        public ActionResult ByTime(int? time, int page = 1)
        {
            if (time.Equals(""))//If the user clicks search without entering a category, the LandingRecipes page will be re-displayed.
            {
                TempData["Message"] = "Please Select a Time";
                return View("LandingRecipes");
            }

            var model = db.Recipes.Where(r => r.Timescale < time).ToList().ToPagedList(page, 10);//Returning all recipes that have a timescale less than the user's input.
            return View("GlutenFree",model);
        }


        public ActionResult CheckRecipe(string searchTerm)
        {
            var model =
                db.Recipes
                .Where(r => searchTerm == null || r.Name.StartsWith(searchTerm)) //The first part is saying that if the paramater is null (i.e. no specific search was entered), then return all the results.
                .Select(r => new Recipe //Creating an anonymous type.
                {
                    Id = r.Id,//These properties are coming from the Model and we are assigning to them whatever is the corresponding value from 'r', which is coming from our '_db.Restaurants'.
                    Name = r.Name,
                    Description = r.Description,
                    Instructions = r.Instructions,
                    Ingredients = r.Ingredients,
                    Timescale = r.Timescale,

                    
                });
            return View("Index", model);
        }

        //This action is used on the 'Quick and easy recipes' option on the home page
        public ActionResult Time(int page = 1)
        {
            var model = db.Recipes.Where(r => r.Timescale < 20).ToList().ToPagedList(page, 10);
            ViewBag.Title = "Under 20 Minutes";
            return View("GlutenFree", model);
        }

        public ActionResult GlutenFree(int page = 1)
        {
            var model = db.Recipes.Where(r => r.Category == "Gluten Free").ToList().ToPagedList(page, 10);
            ViewBag.Title = "Gluten Free";
            return View(model);
        }

        public ActionResult Smoothie(int page = 1)
        {
            var model = db.Recipes.Where(r => r.Category == "Smoothie").ToList().ToPagedList(page, 10);
            ViewBag.Title = "Smoothies";
            return View("GlutenFree", model);
        }


        public ActionResult Landing()
        {
            var dictionary = new Dictionary<int, string>//I'm using this dictionary to create values that will populate a DropdownList in the View.
                {
                    { 10, "10" },
                    { 15, "15" },
                    { 20, "20" },
                    { 25, "25" },
                    { 30, "30" },
                    { 40, "40" },
                    { 50, "50" }
                };

            ViewBag.SelectList = new SelectList(dictionary, "Key", "Value");//Being sent through a Viewbag in a key-value pairing.
            return View("LandingRecipes");
        }

         public ActionResult DisplayList(int page = 1)
        {
            return View(db.Recipes.ToList().ToPagedList(page, 10));
        }

        // GET: Recipes
        public ActionResult Index(string search, int page = 1)
        {
            if (search == "")
            {
                return RedirectToAction("DisplayList");//If the search result comes back empty, then all results will be displayed
            }
            else
            {
                var model = db.Recipes
                        .Where(r => search == null || r.Name.StartsWith(search)).ToList().ToPagedList(page, 10);

                //return View(db.Recipes.ToList());
                ViewBag.SearchTerm = search;
                return View("DisplayList", model);
            }
        }

        public ActionResult Category(string category, int page = 1)
        {
            if (category.Equals(""))//If the user clicks search without entering a category, the LandingRecipes page will be re-displayed.
            {
                TempData["Message"] = "Please Select a Category";
                return View("LandingRecipes");
            }
            else
            {
                var model = db.Recipes.Where(r => r.Category == category).ToList().ToPagedList(page, 10);
                return View("GlutenFree", model);
            }
        }

        // GET: Recipes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recipe recipe = db.Recipes.Find(id);
            if (recipe == null)
            {
                return HttpNotFound();
            }
            return View(recipe);
        }

        // GET: Recipes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Recipes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Recipe recipe, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    file.SaveAs(HttpContext.Server.MapPath("~/Images/")
                                                          + file.FileName);
                    recipe.ImagePath = file.FileName;
                }

                recipe.UserName = User.Identity.Name;//This allows me to match the Recipe's UserName property with the UserName of the currently logged in user.

                recipe.Date = DateTime.Today;
                db.Recipes.Add(recipe);
                db.SaveChanges();
                return RedirectToAction("DisplayList");
            }

            return View(recipe);
        }

        // GET: Recipes/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recipe recipe = db.Recipes.Find(id);
            if (recipe == null)
            {
                return HttpNotFound();
            }
            return View(recipe);
        }

        // POST: Recipes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Recipe recipe)
        {
            if (ModelState.IsValid)
            {
                recipe.UserName = User.Identity.Name;
                db.Entry(recipe).State = EntityState.Modified;//Tells the Entity Framework not to treat this like a new entry but tather like an existing one that is being updated.
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(recipe);
        }

        // GET: Recipes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recipe recipe = db.Recipes.Find(id);
            if (recipe == null)
            {
                return HttpNotFound();
            }
            return View(recipe);
        }

        // POST: Recipes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Recipe recipe = db.Recipes.Find(id);
            db.Recipes.Remove(recipe);
            db.SaveChanges();
            return RedirectToAction("DisplayList");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OdeToFood/Controllers/ReviewsController.cs
using OdeToFood.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace OdeToFood.Controllers
{
    public class ReviewsController : Controller
    {
        OdeToFoodDb _db = new OdeToFoodDb();

        //[ChildActionOnly]//This would ensure that this contoller cannot be called through the URL
        //public ActionResult BestReview()//This action will display the besst rated review from the lisr of review, at the bottom of every page (because it is called from the shared _Layout View).
        //{
        //    var bestReview = from r in _reviews
        //                     orderby r.Rating descending
        //                     select r;

        //    return PartialView("_Review", bestReview.First());
        //}

        public ActionResult SeeReviewersRestaurantsReviews(string r)
        {
            var model = _db.Reviews.Where(m => m.ReviewerName == r);
            return View("GetMyReviews", model);
        }


        public ActionResult GetMyReviews(int page = 1)
        {
            var UserReviews = _db.Reviews.Where(m => m.ReviewerName == User.Identity.Name).ToList().ToPagedList(page, 10);
            return View(UserReviews);
        }
        
        public ActionResult BestReviews(int page = 1)
        {
            var model = _db.Reviews.Where(m => m.Rating == 10).ToList().ToPagedList(page, 10);
            return View(model);
        }

        public ActionResult Test(int restaurantId)
        {
            //RestaurantReview review = new RestaurantReview();
            return View("_Test");
        }

        // GET: Reviews
        public ActionResult Index([Bind(Prefix = "id")] int restaurantId)  //This says when looking for the restaurantId parameter value, instead look for something called 'id'.
        {
            var restaurant = _db.Restaurants.Find(restaurantId);
            if (restaurant != null)
            {
                return View(restaurant);

            }
            return HttpNotFound();
        }

       

        [HttpGet]
        
        public ActionResult Create(int restaurantId)
        {
            return PartialView("_Test");
        }
        
        
        [HttpPost]
        public ActionResult Create(RestaurantReview review)
        {
            if (ModelState.IsValid)
            {
                review.ReviewerName = User.Identity.Name;
                _db.Reviews.Add(review);//If IsValid returns true, then add this review to the Reviews collections
                _db.SaveChanges();//This will actually save it to the database
                return RedirectToAction("Index", new { id = review.RestaurantId });//Second paramter ensures the user can then view their newly entered review (as we've passed the id through).
                

            }
            return View(review);//Passing 'review' as a parameter here ensures that the user doesn't lose their already inputted data.
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = _db.Reviews.Find(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(RestaurantReview review)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(review).State = EntityState.Modified;//Here is a review i want you to track so you can make changes in the database, but its not a new review so I don't want it inserted into the database. Instead its a review that's already in the database.
                _db.SaveChanges();
                return RedirectToAction("Index", new { id = review.RestaurantId });
            }
            return View(review);
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RestaurantReview restaurantReview = _db.Reviews.Find(id);
            if (restaurantReview == null)
            {
                return HttpNotFound();
            }
            return View(restaurantReview);
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);    
        }


    }
}

OdeToFood/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>


@using (Html.BeginForm("Search", "Restaurant", FormMethod.Get))
{
    <b>Search By:</b>
    @Html.RadioButton("searchBy", "Restaurant", true) <text>Restaurant</text>
    @Html.RadioButton("searchBy", "Review") <text>Recipe</text>
    <br />
    @Html.TextBox("search") <input type="submit" value="search" />

}

<p>Use this area to provide additional information.</p>


<form action="~/Home/Score" method="post">
    <input type="search" name="input" />
    <input type="submit" value="Search By Number rating" />
</form>

OdeToFood/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

OdeToFood/Views/Home/Index.cshtml
@model IEnumerable<OdeToFood.Models.RestaurantListViewModel>

@{
    ViewBag.Title = "Home Page";
}

@*<form method="get" action="@Url.Action("Index")"
          data-otf-ajax ="true" data-otf-target="#restaurantList"><!--By using this get method, the search is being put into the query string. Becaue we are searching, a get request is fine. If we were submitting and saving data, then a post request would be needed.-->

        <input type="search" name="searchTerm" data-otf-autocomplete ="@Url.Action("AutoComplete")"/>
        <input type="submit" value="Search By Name" />
    </form>*@



<div class="wrapper">


    <!--Jumbotron-->
    <div class="jumbotron jumbotron-fluid bg-success text-white">
        <div class="container text-sm-center pt-5">
            <h1 class="display-2">Vegan World</h1>
            <p class="lead">Ireland's Guide to Vegan Options</p>
            <div class="btn-group mt-2" role="group" aria-label="Basic example">
                @*<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#register">Register Now</button>*@
                @*<a class="btn btn-secondary btn-lg" href="#speakers">See Speakers</a>*@
                <a href="@Url.Action("Index", "Restaurant")" class="btn btn-primary btn-lg"> Restaurants</a>
                <a href="@Url.Action("Landing", "Recipes")" class="btn btn-secondary btn-lg">Recipes</a>
            </div>
        </div>
    </div>
    <!-- /Jumbotron-->

    <div class="pt-4 pl-5">
        <h1 class="my-5 text-muted display-4 text-center">Welcome</h1>
        <p>
            Welcome to the Irish Vegan. As any Irish vegan knows, it can be extremely difficult to find what you are looking for.<br /> This website
            hopes to help you by highlighting the options that do exist. We have plenty of restauants and recipes for you to check out so go
            ahead and get started by clicking on the links above.
        </p>
    </div>

    <div class="container pt-5">

        <!--Explore-->
        <h1 id="explore" class="display-4 text-center my-5 text-muted">Explore</h1><!--my-5 means margin padding on the y-axis (top and bottom)-->
        <!--In the below grid, each column spans the width of 6 columns. Since there is only space for 12 columns per line, this will force the layout to only have 2 columns per line. Thus, it will cause our layout to have 3 lines each with two columns (i.e. two pictures per line) In the large format each column spans 4 columns so therefore there will be 3 columns per line-->
        <div class="row">

            <div class="col-md-6 col-lg-4">
                <div class="card mb-3">
                    <img class="card-img-top img-fluid" src="~/images/restaurant.jpg" alt="Card image cap"><!--img-fluid allows the image to scale with its column. Otherwise, the original size of the image may burst out of the card container-->
                    <div class="card-block">
                        <h4 class="card-title  text-center"><a href="@Url.Action("Top", "Restaurant")" class="btn btn-primary btn-lg"> Top 5 Restaurants</a></h4>
                        <p class="card-text">Click here to see the top 5 rated restaurants in Ireland.</p>
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-lg-4">
                <div class="card mb-3">
                    <img class="card-img-top img-fluid" src="~/images/Dublin2.jpeg" alt="Card image cap"><!--img-fluid allows the image to scale with its column-->
                    <div class="card-block">
                        <h4 class="card-title text-center"><a href="@Url.Action("County", "Restaurant")" class="btn btn-primary btn-lg"> Dublin Restaurants</a></h4>
                        <p class="card-text">Dublin is home to the majority of vegan stores and restaurants.</p>
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-lg-4">
                <div class="card mb-3">
                    <img class="card-img-top img-fluid" src="~/images/Reviews2.jpg" alt="Card image cap"><!--img-fluid allows the image to scale with its column-->
                    <div class="card-block">
                        <h4 class="card-title  text-center"><a href="@Url.Action("BestReviews", "Reviews")" class="btn btn-primary btn-lg">10 Star Reviews</a></h4>
                        <p class="card-text">Why not have a look at our 10 star restaurant reviews.</p>
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-lg-4">
                <div class="card mb-3">
                    <img class="card-img-top img-fluid" src="~/images/Clock2.jpeg" alt="Card image cap"><!--img-fluid allows the image to scale with its column-->
                    <div class="card-block">
                        <h4 class="card-title  text-center"><a href="@Url.Action("Time", "Recipes")" class="btn btn-primary btn-lg">Quick and Easy Recipes</a></h4>
                        <p class="card-text">Only have 20 minutes? Then try these quick and easy recipes.</p>
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-lg-4">
                <div class="card mb-3">
                    <img class="card-img-top img-fluid" src="~/images/Gluten2.jpeg" alt="Card image cap"><!--img-fluid allows the image to scale with its column-->
                    <div class="card-block">
                        <h4 class="card-title text-center"><a href="@Url.Action("GlutenFree", "Recipes")" class="btn btn-primary btn-lg">Gluten Free Recipes</a></h4>
                        <p class="card-text">Have you gone Gluten Free? Then we've got you covered.</p>
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-lg-4">
                <div class="card mb-3">
                    <img class="card-img-top img-fluid" src="~/images/Smoothie.jpeg" alt="Card image cap"><!--img-fluid allows the image to scale with its column-->
                    <div class="card-block">
                        <h4 class="card-title  text-center"><a href="@Url.Action("Smoothie", "Recipes")" class="btn btn-primary btn-lg">Delicious Smoothies</a></h4>
                        <p class="card-text">A selection of refreshing Smoothies that are sure to satisfy your tastebuds.</p>
                    </div>
                </div>
            </div>
        </div>
        <!--Speakers-->

    </div>  <!--/Container-->
</div>






















@*<section>

        <div class="image">
            <img src="~/Images/Vegan Image.png" width="100%" height="320" alt="Vegan Image" />
        </div>



        <div class="left">

        </div><!--end of left-->


        <a>
            <div class="right">

                <!--<img src="images/envelope.jpg" width="30%" height="80" alt="envelope">-->
                <div><i class="fa fa-envelope-o fa-5x" aria-hidden="true"></i></div>

            </div>
        </a><!--end of right class-->


    </section>*@






@*@using (Ajax.BeginForm(
                new AjaxOptions
                {
                    HttpMethod = "get",
                    InsertionMode = InsertionMode.Replace,
                    UpdateTargetId = "restaurantList"
                }))
    {
    <input type="search" name="searchTerm" />
    <input type="submit" value="Search By Name" />
    }*@

@*@Html.Partial("_Restaurants", Model)*@








@*<div class="jumbotron">
        <h1>ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
    </div>

    <div class="row">
        <div class="col-md-4">
            <h2>Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </div>
    </div>*@

OdeToFood/Views/Home/Score.cshtml
@model IEnumerable<OdeToFood.Models.RestaurantReview>

@{
    ViewBag.Title = "Score";
}

<h2>Restaurants by Rating</h2>

<h4>Number of Results: @Model.ToList().Count</h4>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Rating)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Body)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReviewerName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Rating)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Body)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReviewerName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}
</table>

OdeToFood/Views/Home/_Restaurants.cshtml
@model IEnumerable<OdeToFood.Models.RestaurantListViewModel>


<div id="restaurantList">
    <!--This represnets the area that we want to update when the user searches for something (i.e. Their search term remains in the search box rather than returning to blank)-->
    @foreach (var item in Model)
    {
        <div>
            <h4><a href="Restaurant/Details/@item.Id">@item.Name</a></h4>
            <div>@item.City, @item.Country</div>
            <div>
                Reviews:  @item.CountOfReviews
            </div>
            <hr />
        </div>

    }
</div>